basePath: /
definitions:
  api.DescriptorResponse:
    properties:
      descriptors:
        items:
          type: string
        type: array
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for generating random NPC descriptors.
  title: NPC Descriptor API
  version: "1.0"
paths:
  /api/descriptors:
    get:
      description: returns random NPC descriptors as a JSON list. Optional query param
        'n' (1-10) sets count (default 3). 'lang' sets locale (default 'en').
      parameters:
      - default: 3
        description: Number of descriptors
        in: query
        maximum: 10
        minimum: 1
        name: "n"
        type: integer
      - default: '"en"'
        description: Locale
        in: query
        name: lang
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.DescriptorResponse'
      summary: Get NPC descriptors
swagger: "2.0"
